# Specifieer de versie van de Docker Compose syntax. Versie 3.8 werkt goed met Docker Swarm.
version: '3.8'

# Hier definiëren we alle services (containers) die samen de applicatie vormen.
services:
  # Service CloudShirt webapplicatie.
  cloudshirt-web:
    # De Docker image die we willen draaien. De DOCKER_REGISTRY_URL wordt buitenom ingevuld (door de buildserver).
    image: ${DOCKER_REGISTRY_URL}/cloudshirt-web:latest

    # Publiceer poorten van de container naar de host (EC2 instances).
    ports:
      # Stuur verkeer van poort 80 op de EC2-instance (links) door naar poort 80 in de container (rechts).
      - "80:80"

    # Omgevingsvariabelen die binnen in de container beschikbaar zijn voor de .NET app.
    environment:
      # Draai de applicatie in Productie modus in plaats van Development.
      - ASPNETCORE_ENVIRONMENT=Production
      # Geef de database connection strings door via environment variables, met waarden die we dynamisch invullen (RDS_ENDPOINT, RDS_USERNAME, RDS_PASSWORD).
      - ConnectionStrings__CatalogConnection=Server=${RDS_ENDPOINT};Database=CloudShirtDb;User Id=${RDS_USERNAME};Password=${RDS_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__IdentityConnection=Server=${RDS_ENDPOINT};Database=CloudShirtDb;User Id=${RDS_USERNAME};Password=${RDS_PASSWORD};TrustServerCertificate=True;

    # Gebruik de VPC DNS resolver zodat AWS hostnames (zoals de RDS endpoint) binnen de container kunnen worden opgezocht.
    dns:
      - 10.0.0.2

    # Instellingen die specifiek gelden wanneer deze compose file als Swarm stack wordt gedeployed.
    deploy:
      #  Het vaste aantal identieke container instanties die we willen draaien.
      mode: replicated
      # Totaal aantal containers van deze service in het hele Swarm cluster.
      replicas: 3
      # Bepaalt wat Swarm moet doen als een container crasht.
      restart_policy:
        # Altijd herstarten, ook bij een clean exit (code 0).
        # 'on-failure' miste gevallen waarbij de .NET app succesvol afsloot maar niet had mogen stoppen.
        condition: any
        delay: 5s
        max_attempts: 10