apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshirt-web
  labels:
    app: cloudshirt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cloudshirt
  template:
    metadata:
      labels:
        app: cloudshirt
    spec:
      containers:
      - name: cloudshirt-web
        image: <REPLACE_WITH_ECR_URL>:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__CatalogConnection
          value: "Server=<REPLACE_WITH_RDS_ENDPOINT>;Database=CloudShirtDb;User Id=adminAWS;Password=Komjenietin123;TrustServerCertificate=True;"
        - name: ConnectionStrings__IdentityConnection
          value: "Server=<REPLACE_WITH_RDS_ENDPOINT>;Database=CloudShirtDb;User Id=adminAWS;Password=Komjenietin123;TrustServerCertificate=True;"
