apiVersion: v1
kind: Secret
metadata:
  name: cloudshirt-secrets
  namespace: default
type: Opaque
stringData:
  CatalogConnection: "Server={{ rds_endpoint }};Database=CloudShirtDb;User Id={{ db_user }};Password={{ db_password }};TrustServerCertificate=True;"
  IdentityConnection: "Server={{ rds_endpoint }};Database=CloudShirtDb;User Id={{ db_user }};Password={{ db_password }};TrustServerCertificate=True;"