apiVersion: v1
kind: Service
metadata:
  name: cloudshirt-web
  namespace: default
spec:
  # type LoadBalancer => AWS maakt automatisch een load balancer met één extern adres.
  type: LoadBalancer
  selector:
    app: cloudshirt-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP