AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Assignment 2 - RDS Postgres Database

Parameters:
  BaseStackName:
    Type: String
    Default: MyBase3

  DatabaseName:
    Description: Name of the database to create at deployment time
    Type: String
    Default: tododb

  UserName:
    Description: Username so it can be set at deploy time
    Type: String
    Default: postgres

  Password:
    Description: Password so it can be set at deploy time
    Type: String
    NoEcho: true

  DatabaseClass:
    Description: Database Class so the instance type can be set at deployment time
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t2.micro, db.t3.micro, db.t4g.micro]

Resources:
  # 1. Security Group voor de Database
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres (5432) access from VPC
      VpcId: 
        Fn::ImportValue: !Sub "${BaseStackName}:VPC"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16 

  # 2. Een tweede Subnet
  SecondPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Sub "${BaseStackName}:VPC"
      CidrBlock: 10.0.52.0/24
      AvailabilityZone: !Select [1, !GetAZs ''] 
      Tags:
        - Key: Name
          Value: SecondPrivateSubnetForRDS

  # 3. DB Subnet Group
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS Database
      SubnetIds:
        - Fn::ImportValue: !Sub "${BaseStackName}:MyFirstPrivateSubnet"
        - !Ref SecondPrivateSubnet

  # 4. Parameter Group om MD5 encryptie aan te zetten
  MyPostgresParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "Force MD5 password encryption for older clients"
      Family: postgres17
      Parameters:
        password_encryption: md5

  # 5. De Postgres Database
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 14.12
      DBParameterGroupName: !Ref MyPostgresParameterGroup
      DBInstanceClass: !Ref DatabaseClass
      DBName: !Ref DatabaseName
      MasterUsername: !Ref UserName
      MasterUserPassword: !Ref Password
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false

Outputs:
  DBEndpointAddress:
    Description: RDS Endpoint Address
    Value: !GetAtt MyPostgresDB.Endpoint.Address
  DBEndpointPort:
    Description: RDS Endpoint Port
    Value: !GetAtt MyPostgresDB.Endpoint.Port