# Algemene variabelen voor ansible playbooks
aws_region:   us-east-1
cluster_name: cloudshirt-eks

# Paden (relatief vanuit ansible/)
terraform_dir: ../terraform
k8s_dir:       ../k8s
rendered_dir:  ./rendered
logs_dir:      ./logs

# Database-gegevens (gelijk aan variables.tf).
# Deze kunnen ook met ansible-vault versleuteld opgeslagen worden.
db_user:     adminAWS
db_password: Komjenietin123